### ISSUE TITLE
missing related items in taxonTreatments

### ISSUE THREAD

**Issue by myrmoteras** [plazi/Biodiversity-Literature-Repository#91]
@gsautter in this treatement https://zenodo.org/record/4326615#.X9nf7thKiPo

there now some links missing: 
* the link to the source article deposit in BLR https://zenodo.org/record/4326611 
* the link to the figures cited in the treatment https://zenodo.org/search?page=1&size=20&q=Ophioderma%20hendleri%20 
* originally, there has been a llink from there to the article in Zenodo
* 
![image](https://user-images.githubusercontent.com/4609956/102339332-4bd72500-3f95-11eb-8b9c-95cad1e0520d.png)

or are they added in a later moment?

**Comment by gsautter** [comment]
The links are there now ... since the links (including all deposition numbers and DOIs of figures and treatments) are written into the document asynchronously, pushing the treatments to Zenodo right on upload will necessarily incur a little delay ...
The asynchronous write-back is the only way of distributing _all_ external links (DOIs, GBIF data set ID, etc.) to _all_ other export destinations in a single document update ... implemented this way last September in Geneva.
